name: FoodHut Unit Tests

on:
  push:
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.4.27
        env:
          MARIADB_ROOT_PASSWORD: 12345678
          MARIADB_DATABASE: food-hut-adonis
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Copy .env
        run: cp .env.example .env
      - name: Install dependencies
        run: npm install
      - name: Build
        run: node ace build --production
      - name: Run migrations and Execute tests
        env:
          DB_CONNECTION: mysql
          MYSQL_PORT: 3307
          MYSQL_USER: root
          MYSQL_PASSWORD: 12345678
          MYSQL_DB_NAME: food-hut-adonis
        run: |
          node ace migration:fresh --seed
          node ace test
      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/node@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --all-projects
      #     command: test
  deploy-production:
    name: Deploy Project to PRODUCTION Server
    runs-on: ubuntu-latest
    needs: [unit_tests]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        env:
            DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
            PAT: ${{ secrets.PAT }}
            DEPLOY_PATH_PRODUCTION: ${{ secrets.DEPLOY_PATH_PRODUCTION }}
            SERVER_JSON: ${{ secrets.SERVER_JSON }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOT_ENV, PAT, DEPLOY_PATH_PRODUCTION
          script: |
            sudo mkdir -p /tmp/production/food-hut-adonisjs
            sudo chmod -R 777 /tmp/production/food-hut-adonisjs
            cd /tmp/production && git clone https://$PAT@github.com/ikechukwukalu/food-hut-adonisjs.git
            cd /tmp/production/food-hut-adonisjs
            sudo git checkout main
            sudo npm install
            sudo node ace migration:fresh --seed
            sudo npm run build
            sudo rm -r $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs-old
            sudo mv $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs-old
            sudo mkdir -p $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs
            sudo cp -r /tmp/production/food-hut-adonisjs/build/* $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs
            sudo rm -r /tmp/production/food-hut-adonisjs
            cd $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs
            sudo touch .env
            echo "$DOT_ENV" | sudo tee /tmp/production/food-hut-adonisjs/.env
            sudo touch server.json
            echo "$SERVER_JSON" | sudo tee /tmp/production/food-hut-adonisjs/server.json
            sudo chmod -R 0755 $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs
            pm2 restart food-hut-adonisjs

