name: FoodHut Unit Tests

on:
  push:
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.4.27
        env:
          MARIADB_ROOT_PASSWORD: 12345678
          MARIADB_DATABASE: food-hut-adonis
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Copy .env
        run: cp .env.example .env
      - name: Install dependencies
        run: npm install
      - name: Run migrations and Execute tests
        env:
          DB_CONNECTION: mysql
          MYSQL_PORT: 3307
          MYSQL_USER: root
          MYSQL_PASSWORD: 12345678
          MYSQL_DB_NAME: food-hut-adonis
        run: |
          node ace migration:fresh --seed
          node ace test
      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/node@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --all-projects
      #     command: test
  build:
    runs-on: ubuntu-latest
    needs: [unit_tests]
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Build
        run: npm run build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: build/
          remote_path: ${{ secrets.DEPLOY_PATH_PRODUCTION }}/food-hut-adonisjs
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
  deploy-production:
    name: Deploy Project Server
    runs-on: ubuntu-latest
    needs: [unit_tests, build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        env:
            DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
            PAT: ${{ secrets.PAT }}
            DEPLOY_PATH_PRODUCTION: ${{ secrets.DEPLOY_PATH_PRODUCTION }}
            SERVER_JSON: ${{ secrets.SERVER_JSON }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOT_ENV, PAT, DEPLOY_PATH_PRODUCTION
          script: |
            cd $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs
            sudo touch .env
            echo "$DOT_ENV" | sudo tee $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs/.env
            sudo node ace migration:fresh --seed
            sudo touch server.json
            echo "$SERVER_JSON" | sudo tee $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs/server.json
            sudo chmod -R 0755 $DEPLOY_PATH_PRODUCTION/food-hut-adonisjs
            sudo pm2 start server.json --watch

